strict: true
theme: readthedocs
site_name: Anki Sync Server
site_description: Self-hosted Anki Sync Server.
site_author: Anki Community
site_url: https://ankicommunity.github.io/anki-sync-server
repo_url: https://github.com/ankicommunity/anki-sync-server
docs_dir: src
site_dir: build
plugins:
  - mkdocs-jupyter